### ISSUE TITLE
Problem with heic files from the stock camera app from Oppo Find X5 Pro

### ISSUE THREAD

**Issue by dhcgn** [ente-io/photos-web#1190]
I uploaded a .heic picture with the android app to my account. When viewing this picture on any other way than on this app, I get visual artefacts after the preview image disappears. (See screenshots)

When uploading this image with the browser, the preview has this visual artefacts too, but the app can view this image without these artefacts. (See video)

The image was shot with the stock camera app from Oppo Find X5 Pro.

## Firefox

![firefox (Custom)](https://github.com/ente-io/photos-web/assets/6566207/c2fc2dfc-30bf-4d87-a255-306ece16f297)

## Chrome

![chrome (Custom)](https://github.com/ente-io/photos-web/assets/6566207/f6d62657-4c7f-4108-bea2-2315078d90b0)

## Desktop App

![desktop_app (Custom)](https://github.com/ente-io/photos-web/assets/6566207/7472effd-0403-4081-aad7-254d48e9e005)

## Video when pic was uploaded in browser and viewed in app

https://github.com/ente-io/photos-web/assets/6566207/af14dce1-a4b1-4204-8feb-0937a3103853

## File info

[mediainfo.json.txt](https://github.com/ente-io/photos-web/files/11782120/mediainfo.json.txt)

## File

[IMG20230618143510.heic.zip](https://github.com/ente-io/photos-web/files/11782155/IMG20230618143510.heic.zip)

**Comment by vishnukvmd** [comment]
Hey @dhcgn thanks for sharing a sample file! Will take a look and get back to you

**Comment by abhinavkgrd** [comment]
Hey @dhcgn, so it seems like an issue with the `libheif` library we are using for converting HEIC files for preview on the web/windows app. 

we have raised an [issue](https://github.com/strukturag/libheif/issues/908) with them.

Also in the meantime, we are investigating how we could bundle native `libheif` / `imageMagick` binary with the Windows app to improve HEIC and raw format support. 

Will let you know as soon as we are make any progress with it.
