### ISSUE TITLE
IOS hires loading bug

### ISSUE THREAD

**Issue by bericbone** [ente-io/photos-web#1232]
On IOS, the image often fails to load in hires when scrolling through images. You need to go ahead 1 or 2 pics and back again for the image to update to full res.

**Comment by ua741** [comment]
> On IOS, the image often fails to load in hires when scrolling through images. You need to go ahead 1 or 2 pics and back again for the image to update to full res.

@bericbone
Assuming that you are referring to the mobile app, can you please share the logs with us (Settings -> Support -> Report a bug).. We will take a look what's happening. 

If the images are live photos, then at times it can take few sections to download the original assets (image and video).

**Comment by mnvr** [comment]
I don't think there is a known issue around this on mobile, and the customer who has opened this hasn't followed up for a few months, so closing. Please reopen if it is still happening!
