### ISSUE TITLE
Login session expires too quickly

### ISSUE THREAD

**Issue by bericbone** [ente-io/photos-web#1233]
Login session expires after not even 24 hours. Please update it to at least a few days or a week, or give me the option to do so.

**Comment by abhinavkgrd** [comment]
Hi @bericbone, So, we don't auto expire sessions. 

Can you please share the logs with us (Sidebar -> Debug Logs).. We will take a look what's happening.

**Comment by httpjamesm** [comment]
> Hi @bericbone, So, we don't auto-expire sessions.
> 
> Can you please share the logs with us (Sidebar -> Debug Logs) to [support@ente.io](mailto:support@ente.io)? We will take a look at what's happening.

I believe they are referring to the encryption data being cleared when the session or all tabs are closed, thus requiring the user to enter the password again

**Comment by mnvr** [comment]
We're using session storage to store these credentials. There isn't anything immediate we can do about this short of coming up with an alternative authentication flow in some way. Closing this for now.
