### ISSUE TITLE
modals are not clickable after opening the 2nd time

### ISSUE THREAD

**Issue by szamanr** [ente-io/photos-web#1269]
## problem
cannot click any button in the modal. example modals: confirm delete, fix time.
happens only the 2nd time the modal is open.
trying to click performs the zoom action, as if the modal was not there.
![ente cant click](https://github.com/ente-io/photos-web/assets/2622838/3ff4a7b4-00d9-40ed-bc2b-c54dbceb9181)

## to reproduce
- go to gallery: https://web.ente.io/gallery
- click on a photo to open it
- click the trash button
- click "cancel"
- click the trash button again

### expected result
i can click "move to trash" or "cancel" and it performs the action

### actual result
- i see a zoom cursor when hovering over the modal
- buttons are not clickable
- cannot perform any action

## details
firefox 115 on linux ubuntu 20.04
happens with different modals.
it never happens the first time, but always on the second time and doesn't go away until i refresh the page. this makes it impossible e.g. to delete more than 1 photo.

**Comment by abhinavkgrd** [comment]
Heyy @szamanr, unfortunately, we are unable to reproduce this issue on our end. Can you try to use the desktop app/ different browser, to eliminate that it's not a browser/ extension issue?

We will keep this issue open (add unreproducible flag) and keep an eye to identify such behavior in future

**Comment by szamanr** [comment]
@abhinavkgrd it seems to be a firefox-specific issue and not related to an extension.

- :heavy_check_mark: desktop app (ubuntu 20.04) - works fine
- :heavy_check_mark: brave (v1.56.20 chromium: 115) - works fine
- :x: firefox (116.0.2, firefox for linux) - broken
- :x: firefox private browsing with all extensions turned off - broken

**Comment by abhinavkgrd** [comment]
Heyy @szamanr, Yes the sidebar close issue and this is definitely related. 
This is MUI (https://github.com/mui/material-ui/issues/32286) issue, we had faced the sidebar issue earlier,

They had a hacky patch, which we had implemented, (hence the issue of not being reproducible on Chrome)
but Firefox doesn't have support for `:has` (https://connect.mozilla.org/t5/ideas/when-is-has-css-selector-going-to-be-fully-implemented-in/idi-p/23794)  which is needed for the patch. Hence the issue.

We are looking into a fix for it. In the meantime, please use the desktop app.

Or if want to stick with Firefox.  you can enable a Firefox flag for `:has` support  via`about:config` page, then search and toggle `layout.css.has-selector.enabled` that should patch the issue for now.

**Comment by szamanr** [comment]
i'm no longer experiencing this issue. not sure if this was fixed on your side, by firefox, or something else? i'm on a new device so that could also explain it.
