### ISSUE TITLE
add a feature

### ISSUE THREAD

**Issue by MansourBLUNDERS** [ente-io/photos-web#1297]
the ability to open ente auth directly from ente account from browser 

and thank you so much for the sync feature in the mobile app

**Comment by abhinavkgrd** [comment]
Heyy @MansourBLUNDERS, you can access your auth account on https://auth.ente.io

**Comment by MansourBLUNDERS** [comment]
Thank you.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
