### ISSUE TITLE
iOS image loose EXIF data on import from shared link

### ISSUE THREAD

**Issue by jabossu** [ente-io/photos-web#1303]
Hello devs ! I encountered a small bug when importing pictures from a friend's iphone via the public shared link.
The pictures uploaded this way did not contain any useful exif data : no date, not geolocation, and were simply added to the album using the upload date.

I could reproduce this issue several times.
I used two different but up to date devices, on the safari web browser.
This wasn't the case using the web interface on Linux - Firefox. Didn't test using android.

I'm not sure if this is a bug, or a privacy protection feature from iOS erasing EXIF data on sharing...
If it is, what would be a good workaround ?

Thank you for looking into it !
cheers !

**Comment by vishnukvmd** [comment]
Hey, yes, this is unfortunately an iOS specific issue (/ feature?) that is not unique to ente :(

We're thinking about building a thin app that will let your friend upload photos, without registering an account, but that will take a while. In the meanwhile, a workaround would be to convince your friend to join ente :)

**Comment by abhinavkgrd** [comment]
Closing this in favor of https://github.com/ente-io/photos-web/issues/1519
