### ISSUE TITLE
cannot close sidebar

### ISSUE THREAD

**Issue by szamanr** [ente-io/photos-web#1312]
1. open gallery: https://web.ente.io/gallery
2. click the menu icon to open sidebar

expected:
- i can click the × button to close the sidebar
- i can click outside the sidebar to close it

actual:
- nothing happens when doing either action
- the × is not recognised as a button (no pointer icon on hover)

![ente bug sidebar close](https://github.com/ente-io/photos-web/assets/2622838/e046c499-9abb-434b-9dbd-dafb3bd9cd20)

firefox (116.0.2, firefox for linux, ubuntu 20.04)
not sure if related to #1269, seems similar

**Comment by hellp** [comment]
Yeah, same here. Is whole sidebar is unusable for me. When I try to click *any* menu item, the image that is "behind" the sidebar is zoomed in.

Firefox/Linux

**Comment by vishnukvmd** [comment]
Hey @hellp, could you please check out [our desktop app](https://ente.io/download/desktop) and let us know if the issue persists?

Would like to know if this is specific to a browser. Thank you!
