### ISSUE TITLE
More complex photo editing

### ISSUE THREAD

**Issue by but-whythough** [ente-io/photos-web#1382]
Love the app, but access more photo editing options would be a great addition, as well as having access photo editing on all platforms, it appears at the moment there is no editing of photo's on the desktop and web. 

Ideal features: 
Cross-platform editing
preset filters
aspect ratio presets for cropping
Contrast
white point
black point
highlights 
warmth
tint
Vignette

**Comment by vishnukvmd** [comment]
We could potentially integrate [tui.image-editor](https://github.com/nhn/tui.image-editor).

**Comment by but-whythough** [comment]
that looks great! not sure how well mobile optimized it us but has a lot of good features

**Comment by abhinavkgrd** [comment]
heyy, @but-whythough , we have added an editor for desktop and web😄 , https://ente.io/blog/introducing-web-desktop-photo-editor/
