### ISSUE TITLE
More payment options

### ISSUE THREAD

**Issue by YessirWhatever0** [ente-io/photos-web#1391]
Why I can't pay you with BTC, XMR or USDT?
It's a great service but I can't pay for it

**Comment by vishnukvmd** [comment]
Hey, we do support subscriptions with BTC – [ente.io/faq/subscription/crypto](https://ente.io/faq/subscription/crypto/)

If you'd like to subscribe, please drop a mail to `crypto@ente.io` citing the plan of your choice, and we'll be happy to help you out!
