### ISSUE TITLE
How sharing links/email/adding viewers/etc works in regards to e2e?

### ISSUE THREAD

**Issue by gcb** [ente-io/photos-web#1477]
Is there any explanation of the finer details?

Also, while looking for an answer on source, i see that e2e seems to mean "uploader" and "ente"? is this correct? I assumed it was "uploader" to "uploader"... Am i wrong on that way to read it?

I started from the collections service, which seem it have all the data it needs to decrypt:

https://github.com/ente-io/photos-web/blob/f2f1d7168f1f9ca730286ed69f8b4c9c58b3c723/apps/photos/src/services/collectionService.ts#L196C53-L196C53
`return await getCollectionWithSecrets(collection, key);`

which is started from 
https://github.com/ente-io/photos-web/blob/f2f1d7168f1f9ca730286ed69f8b4c9c58b3c723/apps/photos/src/services/collectionService.ts#L334
and the key parameter is just `const key = await getActualKey();`

https://github.com/ente-io/photos-web/blob/main/packages/shared/user/index.ts#L6
which just gets it from session.

**Comment by vishnukvmd** [comment]
Hey, you can find more information regarding how e2ee sharing works with other Ente users here: https://ente.io/architecture/#sharing

We've documented our architecture for public links here: https://ente.io/blog/building-shareable-links/

If you've any follow up questions, please reopen this issue!
