### ISSUE TITLE
Add Ability to Make Sub-Albums within Albums - Following a Traditional Directory Structure

### ISSUE THREAD

**Issue by wyatt00** [ente-io/photos-web#1495]
I think the ability to *optionally* create sub-albums within albums would help with photo organization immensely. I've been finding myself wanting sub-albums while organizing my photos for awhile now, and I think it would be a nice touch to have in comparison with other photo storage solutions.

**Comment by abhinavkgrd** [comment]
closing this in favor of https://github.com/ente-io/photos-web/issues/1518
