### ISSUE TITLE
Smart search by image content

### ISSUE THREAD

**Issue by muety** [ente-io/photos-web#1524]
Google Photos and Immich have the ability to search images by their contents, e.g. search for "car" and find all pictures containing cars. See https://immich.app/docs/features/search. This is usually powered by a image-text model, such as [CLIP](https://huggingface.co/docs/transformers/model_doc/clip) models. Would love to have this!

**Comment by vishnukvmd** [comment]
Hey, this is already available on our desktop app - https://ente.io/blog/image-search-with-clip-ggml/

Executing search within the browser has additional complexity attached to it, since unlike Google Photos and Immich, we don't have access to your data on our servers, and all the indexing and search happens on the client. So this is currently not on our roadmap at the moment. Sorry!

I hope the desktop app will do the job for now!

**Comment by muety** [comment]
I understand! Thanks for the quick reply. What's the roadmap for getting the CLIP-based image search to mobile?

**Comment by vishnukvmd** [comment]
We've pushed out a beta on Android where you can query the items indexed on desktop. You can enable this from `Settings > Advanced > Machine Learning`.

Support for indexing and querying on all platforms is coming soon (hopefully the next month 🤞)

**Comment by muety** [comment]
Just tried the magic search, but doesn't seem to work very reliable? I searched for "car" and got a bunch of results, even though none of them contains anything that remotely looks like a car :thinking:

**Comment by vishnukvmd** [comment]
Could you search for longer strings, like "red car", and let me know if the results are any better?

**Comment by muety** [comment]
Tried that, but not really. I only have a few pictures in my library (because only for testing). When searching for "red car" I don't get any false positives (no red cars in my library). When searching for "bicycle" I get a a false negative (one photo containing a bicycle). When searching for "blue shirt" I get a false negative and a false positive (photo with me wearing a blue shirt is missed, but instead photo of me wearing a gray shirt is returned).

**Comment by vishnukvmd** [comment]
Could you please let me know which platform (OS) you're on? Thanks!

**Comment by muety** [comment]
Fedora 39 Linux, using the latest `.rpm` Package. Log file attached.

[ente.log.zip](https://github.com/ente-io/photos-web/files/13793073/ente.log.zip)

**Comment by muety** [comment]
> https://josephrocca.github.io/clip-image-sorter/

Awesome tool, didn't know about that!

Actually, both the image sorter web tool as well as Immich return pretty much the exact same (poor) results. So definitely not a problem specific to Ente. Still curious why results are so bad :thinking:.
