### ISSUE TITLE
List of people I've shared an album with

### ISSUE THREAD

**Issue by supersunken** [ente-io/photos-web#1593]
Is there a way to see who I've shared an album with? I only see the ability to share an album but not who've I've shared it with. Also is there a way to see who has viewed the album I've shared with?

**Comment by abhinavkgrd** [comment]
>Is there a way to see who I've shared an album with? 

You can see the people you have shared the album with by clicking on the email row, in the share screen  
<img width="370" alt="image" src="https://github.com/ente-io/photos-web/assets/46242073/46850e57-29e6-4dd3-b329-f6cc6159e94f">
<img width="394" alt="image" src="https://github.com/ente-io/photos-web/assets/46242073/b91591ed-8255-4c41-9923-1ca9ad75bdd1">

> Is there a way to see who has viewed the album I've shared with? 

 We currently don't have this

**Comment by supersunken** [comment]
Does the viewer need to first open the link? I added a viewer but do not see the viewer listed under "Share Album"

**Comment by abhinavkgrd** [comment]
> Does the viewer need to first open the link? I added a viewer but do not see the viewer listed under "Share Album"

Ohh, I think, you have created a public link to share the album, public links can be viewed by anyone with whom you share the link, without any authentication.

So, we can't track who has opened them. 

The screenshots I shared were for email share, where you can share the album with specific people and only they can view them.

**Comment by supersunken** [comment]
No, I created an email share. 

![image](https://github.com/ente-io/photos-web/assets/12675944/ac91e912-71d8-4f2c-ad8e-526957d49824)

From there I added an email address. 

![image](https://github.com/ente-io/photos-web/assets/12675944/454aed36-eb33-451f-9ce3-ac8a7ec0066a)

But none are listed. 

I do see a spinner next to the email enput, not sure what the spinner is doing.

![image](https://github.com/ente-io/photos-web/assets/12675944/fcf742e6-53bd-4965-bb13-bef89b7b8b3b)


Clicking on Add views seems to add but doesn't list the added viewer.

**Comment by supersunken** [comment]
It seems just after clicking on the Add viewers button, I see an error message in red but the panel for Add Viewers closes so quickly that I don't know what the error is. I tried adding my own email (secondary account) and I never receive the invite.

**Comment by supersunken** [comment]
Are you able to take a look into my account why I'm unable to share albums? I just upgraded to 100GB. This would be a deal breaker for not being able to share. If the Add View panel didn't close so quickly after adding, I'd be able to see what the error message is.

**Comment by vishnukvmd** [comment]
Hey @supersunken, could you please write to support@ente.io from your registered email address? We'd be happy to help you out!

**Comment by abhinavkgrd** [comment]
> Add Viewers closes so quickly that I don't know what the error is

hey @supersunken, have fixed this. you should be able to see the error now.
